 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/interfaces", type: :request do
  
  # Interface. As you add validations to Interface, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Interface.create! valid_attributes
      get interfaces_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      interface = Interface.create! valid_attributes
      get interface_url(interface)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_interface_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      interface = Interface.create! valid_attributes
      get edit_interface_url(interface)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Interface" do
        expect {
          post interfaces_url, params: { interface: valid_attributes }
        }.to change(Interface, :count).by(1)
      end

      it "redirects to the created interface" do
        post interfaces_url, params: { interface: valid_attributes }
        expect(response).to redirect_to(interface_url(Interface.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Interface" do
        expect {
          post interfaces_url, params: { interface: invalid_attributes }
        }.to change(Interface, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post interfaces_url, params: { interface: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested interface" do
        interface = Interface.create! valid_attributes
        patch interface_url(interface), params: { interface: new_attributes }
        interface.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the interface" do
        interface = Interface.create! valid_attributes
        patch interface_url(interface), params: { interface: new_attributes }
        interface.reload
        expect(response).to redirect_to(interface_url(interface))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        interface = Interface.create! valid_attributes
        patch interface_url(interface), params: { interface: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested interface" do
      interface = Interface.create! valid_attributes
      expect {
        delete interface_url(interface)
      }.to change(Interface, :count).by(-1)
    end

    it "redirects to the interfaces list" do
      interface = Interface.create! valid_attributes
      delete interface_url(interface)
      expect(response).to redirect_to(interfaces_url)
    end
  end
end
